version: "3"

services:
  sftp:
    container_name: 'sftp'
    hostname: 'sftp'
    image: 1000kit/sftp
    ports:
      - "2222:22"
    environment:
      - SFTP_USERS=tkitftp:passwd1234:1001
      
#END
